name: build
on:
  push:
    paths:
      - "**.go"
      - "go.**"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.**"
      - ".github/workflows/build.yml"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with: {go-version: 1.19}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: make build
