name: lint
on:
  push:
    paths:
      - "**.go"
      - "go.**"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.**"
      - ".github/workflows/lint.yml"
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
